name: Deploy Django to Amazon ECS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/**'

env:
  AWS_REGION: ap-southeast-2                   
  ECR_REPOSITORY: django-app-repository           
  ECS_SERVICE: django-app-service                 
  ECS_CLUSTER: production-cluster                 
  ECS_TASK_DEFINITION_FAMILY: django-app-task
  CONTAINER_NAME: django-app

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set Image URL env variable
      run: echo "IMAGE_URL=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image (Load for scanning)
      uses: docker/build-push-action@v6
      with:
        context: ./app
        load: true
        tags: ${{ env.IMAGE_URL }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: '${{ env.IMAGE_URL }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push docker image to Amazon ECR
      run: |
        docker push ${{ env.IMAGE_URL }}

    - name: Download current task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition ${{ env.ECS_TASK_DEFINITION_FAMILY }} \
          --query taskDefinition > raw-task-definition.json

        jq 'del(.taskDefinitionArn, .revision, .status, .registeredAt, .registeredBy, .compatibilities, .requiresAttributes, .requiresCompatibilities)' raw-task-definition.json > clean-task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: clean-task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ env.IMAGE_URL }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
